spring.application.name=SpringConfigClient

server.port=8080

spring.profiles.active=prod

service.name=SpringConfigClient

spring.config.import=configserver:http://localhost:8763
spring.cloud.config.username=configUser
spring.cloud.config.password=password
spring.cloud.config.name=${service.name}
spring.cloud.config.label=1.0.0